### ISSUE TITLE
android GUI broken

### ISSUE THREAD

**Issue by p00rt** [mkg20001/ZeroNet-kivy#2]
so, the three dots that are supposed to be in the top left corner are in the top right corner. What's more, they don't work. Pressing them does nothing. I'm on LineageOS 14.1 based on android 7.1.2 if that matters.
![screenshot_20170711-104109](https://user-images.githubusercontent.com/10347432/28059843-c8d8f166-6625-11e7-84b0-98740e59a039.png)

**Comment by mkg20001** [comment]
They also don't have a purpose right now. That's why it's still alpha. Settings will be coming some day when kivy gets some bugs fixed. (like for example rotation breaking the app)

**Comment by levabala** [comment]
I have the same problem and just no .bit site loads
alpha.. okay)

**Comment by mkg20001** [comment]
The whole thing would be a bit more stable if kivy (https://github.com/kivy/kivy) would fix their bugs
Additionally I'm unable to build due to a compilation error so development is paused

**Comment by crossonrose** [comment]
Moar GUI!

**Comment by BenMcLean** [comment]
Quick general question: Why are you depending on kivy? Maybe you could use something like libGDX's Scene2D to take care of your GUI needs?

**Comment by mkg20001** [comment]
I will rewrite the UI soon. https://github.com/HelloZeroNet/ZeroNet-kivy/issues/20

**Comment by vorticalbox** [comment]
It's been a year since this was reported and it's still an issue.

S8 Android 8.0.0

**Comment by mkg20001** [comment]
This is currently a wontfix as I'm no longer maintaining this app, and
nobody else currently wants to do it.
I'm sorry, but I can't due to lack of time and interest.

Vorticalbox <notifications@github.com> schrieb am Sa., 1. Dez. 2018, 20:26:

**Comment by SigmaTel71** [comment]
Same issue is on Android 8.1 (Moto G5S). Too bad to hear that app is no longer supported.

**Comment by mkg20001** [comment]
This repo is no longer used. Please re-check if the issue still exists and report it [here](https://github.com/HelloZeroNet/ZeroNet-kivy/issues) if it does
