### ISSUE TITLE
Could not close Question mark Info

### ISSUE THREAD

**Issue by MountainMaster** [mkg20001/ZeroNet-kivy#3]
Hey there,

I had problems closing the dialogues behind the yellow "?" . E.g. it was not possible to close the delete site confirmation dialog without "deleting" or "blacklist"

Sony Z5 Compact
Stock 7.1.1
Google Chrome 61.0.3163.98

**Comment by mkg20001** [comment]
This is a mobile ui issue. Try updating zeronet and check if it still occurs.
Currently I can't release new version of zeronet-kivy because an update of kivy broke the building process.

**Comment by mkg20001** [comment]
This repo is no longer used. Please re-check if the issue still exists and report it [here](https://github.com/HelloZeroNet/ZeroNet-kivy/issues) if it does
