### ISSUE TITLE
Android S6 Active on chrome: No such file or directory: '/storage/emulated/0/lib'

### ISSUE THREAD

**Issue by tomachinz** [mkg20001/ZeroNet-kivy#5]
0≡
!
Internal error: OSError: [Errno 2] No such file or directory: '/storage/emulated/0/lib'
UiWebsocket.py line 78 > UiWebsocket.py line 249 > CryptMessagePlugin.py line 89 > builtins.py line 93 > __init__.py line 16 > builtins.py line 93 > openssl.py line 516 > openssl.py line 512 > util.py line 81
×

**Comment by mkg20001** [comment]
This repo is no longer used. Please re-check if the issue still exists and report it [here](https://github.com/HelloZeroNet/ZeroNet-kivy/issues) if it does
