### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by Tvax** [mkg20001/ZeroNet-kivy#7]
Could you publish you app on F-Droid as it will be easier for people like me that don't have any Google Apps installed?

**Comment by ttlygw2018** [comment]
I'm sorry! I don't know how to write programs! So I don't plan to subscribe
to the channel anymore!

2018/3/16 下午4:52，"Tvax" <notifications@github.com>寫道：

**Comment by mkg20001** [comment]
There is a pending RFP issue on f-droid https://gitlab.com/fdroid/rfp/issues/231
There is also an issue on the other ZeroNet-kivy repo https://github.com/HelloZeroNet/ZeroNet-kivy/issues/13

**Comment by mkg20001** [comment]
Has been done
