### ISSUE TITLE
Popups do not respond

### ISSUE THREAD

**Issue by maxizrin** [mkg20001/ZeroNet-kivy#8]
The popups that slide in at the top, asking for confirmation do not work.
The button (for delete, or confirm permission) does darken for a moment, so it seems to be getting pressed, but nothing happens.

Requesting desktop site does not clear the issue.
I'm using Firefox.

Works well on "epic privacy browser".
Could be a Firefox issue.

I'm unable to delete sites, Grant permissions, or anything else that requires the a button pressed on a popup.

**Comment by mkg20001** [comment]
This repo is no longer used. Please re-check if the issue still exists and report it [here](https://github.com/HelloZeroNet/ZeroNet-kivy/issues) if it does
